/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>

export interface CheckIns {
  checked_at: Generated<string>
  created_at: Generated<string>
  focus: string
  id: Generated<number | null>
  now: string
  prep: string
  soul: string
  updated_at: Generated<string>
}

export interface DB {
  check_ins: CheckIns
}
